### ISSUE TITLE
Problem executing umicollapse.jar

### ISSUE THREAD

**Issue by osvaldogc** [Daniel-Liu-c0deb0t/UMICollapse#8]
Hi Daniel,

I am trying to execute UMIcollapse on my samples, but I am facing problems during the execution. Any suggestion, please?

/usr/bin/java -server -Xms16G -Xmx16G -Xss32M -jar /home/ograna/SOFTWARE/UMICollapse/umicollapse.jar -i YCX00009.CLEAN_sorted.bam -o YCX00009.dedup.bam
Arguments	[-i, YCX00009.CLEAN_sorted.bam, -o, YCX00009.dedup.bam]
Exception in thread "main" java.lang.NullPointerException
	at umicollapse.main.Main.main(Main.java:32)

My version of java
 /usr/bin/java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

**Comment by osvaldogc** [comment]
I've just tried another possibility:


/usr/bin/java -server -Xms16G -Xmx16G -Xss32M -jar /home/ograna/SOFTWARE/UMICollapse/umicollapse.jar **bam** -i YCX00009.CLEAN_sorted.bam -o YCX00009.dedup.bam
Arguments	[bam, -i, YCX00009.CLEAN_sorted.bam, -o, YCX00009.dedup.bam]
Exception in thread "main" java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:645)
	at umicollapse.util.SAMRead.getUMI(SAMRead.java:36)
	at umicollapse.main.DeduplicateSAM.deduplicateAndMerge(DeduplicateSAM.java:106)
	at umicollapse.main.Main.main(Main.java:212)

**Comment by Daniel-Liu-c0deb0t** [comment]
Yeah, you will need to explicitly specify `sam`/`bam` or `fastq` as the first argument to let UMICollapse know which mode is being used.

It seems like UMIs are not being found in the read headers of your BAM records. Either the UMI separator in your read header is not `_` (you will need to specify `--umi-sep` with another separator), or you haven't extracted UMIs with UMI-tools before alignment. If you paste one of your BAM records here, perhaps I can try to see what's missing.

**Comment by Daniel-Liu-c0deb0t** [comment]
@osvaldogc Any updates?
